# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame

In [2]:
# load the csv exported data from WeatherPY notebook
cities_df = pd.read_csv("data/city_weather.csv")
cities_df = cities_df.drop(columns="Unnamed: 0")
cities_df

,City,Country,Lat,Lng,Date,Cloudiness,Humidity,Wind Speed,Max Temp
0,Bredasdorp,ZA,-34.53,20.04,1569169666,28,50,6.93,59.00
1,La Ronge,CA,55.10,-105.30,1569169666,20,67,6.93,59.00
2,Longyearbyen,NO,78.22,15.63,1569169667,40,77,10.29,32.00
3,Ushuaia,AR,-54.81,-68.31,1569169429,90,99,6.24,42.80
4,Pipri,IN,24.21,83.02,1569169667,82,79,3.24,80.61
5,Pitimbu,BR,-7.47,-34.81,1569169667,20,54,10.29,84.20
6,Saint George,GR,39.45,22.34,1569169667,20,56,10.29,71.60
7,Tuatapere,NZ,-46.13,167.69,1569169668,100,56,13.00,57.00
8,Punta Arenas,CL,-53.16,-70.91,1569169668,75,75,5.82,42.80
9,Chuy,UY,-33.69,-53.46,1569169668,0,55,12.82,54.15
10,Isangel,VU,-19.55,169.27,1569169668,75,88,5.82,68.00
11,Cape Town,ZA,-33.93,18.42,1569169668,20,58,18.34,61.00
12,Yumen,CN,40.29,97.04,1569169669,0,14,15.61,68.37
13,Yekaterinoslavka,RU,54.34,72.46,1569169669,100,79,17.65,56.31
14,Mahebourg,MU,-20.41,57.70,1569169669,75,88,13.87,71.60
15,Qaanaaq,GL,77.48,-69.36,1569169669,0,52,5.61,24.27
16,Bilibino,RU,68.06,166.44,1569169670,88,96,2.15,18.87
17,Alibag,IN,18.64,72.88,1569169670,20,83,6.93,82.40
18,Saldanha,PT,41.42,-6.55,1569169670,94,44,10.18,68.19
19,Rikitea,PF,-23.12,-134.97,1569169670,100,85,16.62,70.35
20,Tashtyp,RU,52.80,89.89,1569169670,0,90,1.03,45.15
21,Tuim,RU,54.34,89.93,1569169671,0,88,4.56,46.23
22,Busselton,AU,-33.64,115.35,1569169671,100,66,13.31,48.00
23,Altay,CN,47.83,88.13,1569169671,0,30,6.69,54.33
24,Barrow,AR,-38.31,-60.23,1569169671,0,27,8.90,63.15
25,Ribeira Grande,PT,38.52,-28.70,1569169672,75,88,23.04,75.20
26,Zhezkazgan,KZ,47.80,67.71,1569169672,90,87,20.13,51.80
27,Castro,CL,-42.48,-73.76,1569169437,75,70,9.17,46.40
28,Kaitangata,NZ,-46.28,169.85,1569169672,88,57,3.00,52.00
29,Constitucion,MX,23.99,-104.67,1569169672,5,59,2.24,70.00
...,...,...,...,...,...,...,...,...,...
532,Grenfell,AU,-33.90,148.16,1569169778,57,75,2.04,43.17
533,Mushie,CD,-3.02,16.92,1569169778,43,45,0.94,90.87
534,Rusape,ZW,-18.53,32.12,1569169779,3,14,7.11,82.95
535,Qaqortoq,GL,60.72,-46.03,1569169744,0,70,2.24,42.80
536,Zhob,PK,31.34,69.45,1569169779,0,29,8.95,75.93
537,Suleja,NG,9.18,7.18,1569169779,75,69,25.28,73.40
538,Ambovombe,MG,-25.18,46.09,1569169779,0,79,31.16,72.51
539,Cortes,PH,9.28,126.19,1569169780,89,77,5.84,80.61
540,Palana,RU,59.08,159.95,1569169780,100,87,22.03,47.49
541,Stromness,CA,42.87,-79.55,1569169780,75,58,16.11,84.20
542,Vrangel,RU,42.73,133.08,1569169780,100,78,4.36,49.65
543,El Real de Santa Maria,PA,8.11,-77.73,1569169781,100,62,1.07,85.65
544,Kirove,UA,47.83,38.01,1569169781,87,61,16.17,59.37
545,Husavik,CA,50.56,-96.99,1569169781,69,91,3.00,60.01
546,Tiznit,MA,29.70,-9.73,1569169781,0,88,7.67,69.81
547,Timizart,DZ,36.80,4.25,1569169782,100,87,2.51,73.77
548,Ketchikan,US,55.34,-131.65,1569169782,90,93,5.82,53.60
549,Tual,ID,-5.67,132.75,1569169782,0,89,12.71,78.27
550,Fengcheng,CN,40.45,124.07,1569169782,0,66,4.61,53.07
551,Axim,GH,4.87,-2.24,1569169782,100,87,6.58,77.73
552,Meulaboh,ID,4.14,96.13,1569169783,97,81,5.37,81.69
553,Opuwo,NaN,-18.06,13.84,1569169783,95,11,16.71,94.65
554,Hajdunanas,HU,47.85,21.43,1569169783,0,24,4.70,71.60
555,Erzin,TR,36.95,36.20,1569169783,0,34,6.93,81.00
556,Paka,CF,4.15,15.03,1569169784,100,88,3.13,79.35
557,Caravelas,BR,-17.73,-39.27,1569169784,24,63,8.08,78.99
558,Laguna,BZ,16.17,-88.94,1569169784,40,70,6.93,87.80
559,Bayan,CN,36.10,102.26,1569169784,47,60,6.26,47.13
560,West Wendover,US,40.74,-114.07,1569169566,1,46,5.82,53.60
561,Cururupu,BR,-1.82,-44.87,1569169784,60,60,6.17,87.09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Plot Heatmap
fig = gmaps.figure()

# Store latitude and longitude in locations
locations = cities_df[["Lat", "Lng"]]
humidity = cities_df["Humidity"]

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1.5)

fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
# ideal weather conditions is temp between 70-80, wind speed < 10 mph, cloudiness less than 20

ideal_df = cities_df.loc[(cities_df["Max Temp"] > 70) & (cities_df["Max Temp"] < 80)
                        & (cities_df["Cloudiness"] < 25) & (cities_df["Wind Speed"] < 10)] 
ideal_df = ideal_df.reset_index().drop(columns="index")
ideal_df

,City,Country,Lat,Lng,Date,Cloudiness,Humidity,Wind Speed,Max Temp
0,Labuhan,ID,-2.54,115.51,1569169676,9,84,1.97,74.67
1,Crotone,IT,39.09,17.12,1569169678,20,78,8.05,73.40
2,San Quintin,PH,17.54,120.52,1569169679,10,88,2.75,72.15
3,Kapaa,US,22.08,-159.32,1569169679,20,88,5.82,75.20
4,Guerrero Negro,MX,27.97,-114.04,1569169685,0,81,3.40,70.35
5,Bileca,BA,42.87,18.43,1569169685,0,60,9.17,73.40
6,Kununurra,AU,-15.77,128.74,1569169686,1,57,2.82,78.80
7,Pisco,PE,-13.71,-76.20,1569169691,0,30,9.17,71.60
8,Purmerend,NL,52.50,4.96,1569169702,0,53,9.17,79.00
9,Borda da Mata,BR,-22.27,-46.17,1569169714,20,57,4.23,78.80
10,Lompoc,US,34.64,-120.46,1569169717,1,55,2.46,75.99
11,Quetta,PK,30.19,67.02,1569169727,0,13,1.90,73.59
12,Ampanihy,MG,-24.69,44.75,1569169728,0,50,8.66,79.35
13,Tabat,ID,-2.64,115.23,1569169732,0,78,3.11,77.73
14,Kahului,US,20.89,-156.47,1569169734,1,83,5.32,75.99
15,Bac Giang,VN,21.27,106.20,1569169737,0,78,2.24,75.20
16,Denpasar,ID,-8.65,115.22,1569169739,20,88,6.93,77.00
17,Huilong,CN,31.15,106.50,1569169745,0,70,1.99,70.17
18,Sharan,AF,33.15,68.78,1569169748,0,8,6.08,70.35
19,Ceyhan,TR,37.03,35.82,1569169760,0,41,8.05,79.00
20,Lithakia,GR,37.72,20.83,1569169764,20,47,8.05,78.80
21,Kieta,PG,-6.22,155.63,1569169767,6,78,7.65,79.71
22,Ninghai,CN,29.29,121.42,1569169768,0,68,8.95,73.00
23,Sarkand,KZ,45.41,79.91,1569169771,0,17,6.98,75.93
24,Zhob,PK,31.34,69.45,1569169779,0,29,8.95,75.93
25,Hajdunanas,HU,47.85,21.43,1569169783,0,24,4.70,71.60
26,Caravelas,BR,-17.73,-39.27,1569169784,24,63,8.08,78.99

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
# set up the hotel datafram
hotel_df = ideal_df
hotel_df["Hotel Name"] = ""
hotel_df.head()

,City,Country,Lat,Lng,Date,Cloudiness,Humidity,Wind Speed,Max Temp,Hotel Name
0,Labuhan,ID,-2.54,115.51,1569169676,9,84,1.97,74.67,
1,Crotone,IT,39.09,17.12,1569169678,20,78,8.05,73.40,
2,San Quintin,PH,17.54,120.52,1569169679,10,88,2.75,72.15,
3,Kapaa,US,22.08,-159.32,1569169679,20,88,5.82,75.20,
4,Guerrero Negro,MX,27.97,-114.04,1569169685,0,81,3.40,70.35,

In [6]:
# params dictionary to update each iteration
params = {
    "radius": 50000,
    "types": "lodging",
    "key": g_key
}

In [7]:
# Use the lat/lng to identify hotels
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request 
    response = requests.get(base_url, params=params)


    # convert to json
    response_json = response.json()

    # try to get results back, create exception for missing data
    try:
        hotel_df.loc[index, "Hotel Name"] = response_json["results"][0]["name"]
        print("A nearby hotel was found!")

    except (KeyError, IndexError):
        print("No close hotel found, skipping.")


    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)
#     sample URL: https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=50000&types=lodging&key=AIzaSyDRNyoA0GGL6FH-MxZedg4_Yf5grkP03HI&location=-2.54%2C115.51

A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!
A nearby hotel was found!

In [8]:
# view the hotel dataframe complete with hotel names
hotel_df

,City,Country,Lat,Lng,Date,Cloudiness,Humidity,Wind Speed,Max Temp,Hotel Name
0,Labuhan,ID,-2.54,115.51,1569169676,9,84,1.97,74.67,Hotel Gumbil
1,Crotone,IT,39.09,17.12,1569169678,20,78,8.05,73.40,Helios Hotel
2,San Quintin,PH,17.54,120.52,1569169679,10,88,2.75,72.15,Giordion Inn
3,Kapaa,US,22.08,-159.32,1569169679,20,88,5.82,75.20,Courtyard by Marriott Kaua'i at Coconut Beach
4,Guerrero Negro,MX,27.97,-114.04,1569169685,0,81,3.40,70.35,The Halfway Inn
5,Bileca,BA,42.87,18.43,1569169685,0,60,9.17,73.40,Hotel Dubrovnik Palace
6,Kununurra,AU,-15.77,128.74,1569169686,1,57,2.82,78.80,Hotel Kununurra
7,Pisco,PE,-13.71,-76.20,1569169691,0,30,9.17,71.60,Doubletree Resort by Hilton Paracas - Perú
8,Purmerend,NL,52.50,4.96,1569169702,0,53,9.17,79.00,Mövenpick Hotel Amsterdam City Centre
9,Borda da Mata,BR,-22.27,-46.17,1569169714,20,57,4.23,78.80,Hotel Ferraz
10,Lompoc,US,34.64,-120.46,1569169717,1,55,2.46,75.99,Santa Ynez Valley Marriott
11,Quetta,PK,30.19,67.02,1569169727,0,13,1.90,73.59,Hotel Deluxe
12,Ampanihy,MG,-24.69,44.75,1569169728,0,50,8.66,79.35,Sharron Bungalow
13,Tabat,ID,-2.64,115.23,1569169732,0,78,3.11,77.73,Hotel Gumbil
14,Kahului,US,20.89,-156.47,1569169734,1,83,5.32,75.99,Maui Seaside Hotel
15,Bac Giang,VN,21.27,106.20,1569169737,0,78,2.24,75.20,Sofitel Legend Metropole Hanoi
16,Denpasar,ID,-8.65,115.22,1569169739,20,88,6.93,77.00,The Vira Bali Hotel
17,Huilong,CN,31.15,106.50,1569169745,0,70,1.99,70.17,Xiaonanhai Hotel
18,Sharan,AF,33.15,68.78,1569169748,0,8,6.08,70.35,Bilal Shahbaz
19,Ceyhan,TR,37.03,35.82,1569169760,0,41,8.05,79.00,Adana HiltonSA
20,Lithakia,GR,37.72,20.83,1569169764,20,47,8.05,78.80,Hotel Palatino
21,Kieta,PG,-6.22,155.63,1569169767,6,78,7.65,79.71,Arawa Travellers Inn
22,Ninghai,CN,29.29,121.42,1569169768,0,68,8.95,73.00,Kaiyuan New Century Hotel
23,Sarkand,KZ,45.41,79.91,1569169771,0,17,6.98,75.93,Гостиница Сарканд
24,Zhob,PK,31.34,69.45,1569169779,0,29,8.95,75.93,Al Amarat Hotel
25,Hajdunanas,HU,47.85,21.43,1569169783,0,24,4.70,71.60,Aquaticum Debrecen Thermal & Wellness Hotel
26,Caravelas,BR,-17.73,-39.27,1569169784,24,63,8.08,78.99,Pousada Verdes Mares

In [15]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [10]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))